


all:
	gcc -c main.c ping.c dbAccess.c -I/sw/include/postgresql
 
	gcc -o main main.o ping.o dbAccess.o -L/sw/lib/ -lpq -lz -lpthread -lm -lpthread -L/usr/lib -lssl -lcrypto  

clean:
	rm *.o *~ main
